### ISSUE TITLE
1000 file extraction limit

### ISSUE THREAD

**Issue by RoundaboutSnake** [MaikelChan/AFSPacker#18]
It seems to be stuck at only being able to extract the first 1000 files. Is there any way to bypass this?

**Comment by RoundaboutSnake** [comment]
Are you on discord?

**Comment by RoundaboutSnake** [comment]
https://drive.google.com/file/d/10Ws1MsDv6locI_YT4y2_8fCYYP21ZkyR/view?usp=drive_link

That is the final I cannot open.

**Comment by MaikelChan** [comment]
Hi!

Let's try to keep the conversation here so it might help other people that could face a similar issue.

In theory, there shouldn't be a limit in the amount of files. For now, I have requested access to your link.

**Comment by RoundaboutSnake** [comment]
I'm sorry, I didn't mean to disable sharing. It should work now.

**Comment by MaikelChan** [comment]
Hi again,

I just checked the file and I see the problem. That AFS file actually contains several AFS files (18 if I didn't miscount) one after the other. The first of them has exactly 1000 files, just like AFSPacker extracts. So that is working fine. Maybe the file was extracted from the game incorrectly? Or maybe the game is just weird.

You would need to separate the 18 AFS files and extract them individually. Having AFSPacker deal with this kind of problem would be out of the scope of the program.

If you search for the bytes `41 46 53 00` with an hex editor, you will see that there are several instances of the text AFS, which usually indicates the beginning of an AFS file (Not always though, there are some instances where the AFS text appears by coincidence among other gibberish). You could use that to know where to separate each file.

**Comment by RoundaboutSnake** [comment]
Alright, thanks for looking into it. I will try to unpack the file and go from there.
