### ISSUE TITLE
error, cant read beyond files listing

### ISSUE THREAD

**Issue by moth1995** [MaikelChan/AFSPacker#2]
Hi!

first of all thanks for your tool, i'm having and issue trying to read afs files from pes5 and pes6, with pes4 works perfectly

here is my test

with pes4

<img src=https://i.ibb.co/8cnT79c/imagen.png></img>
<img src=https://i.ibb.co/T1pw1fC/imagen.png></img>

with pes5 (same file different game only)

<img src=https://i.ibb.co/YbJwm0s/imagen.png></img>

with pes6 (same file different just more files inside afs)

<img src=https://i.ibb.co/NjDb0S7/imagen.png></img>

the text in red is in spanish, in english means "Error: Invalid characters in the path."

Just for the record, the files are always inside the same folder along with afs packer executable and i test it with and without the optional arg [list_file] but its the same result, also when i open the files with dkz studio or afs explorer i can open them with no issue, maybe its an error when try to read the names for the files? dkz shows pes5 and pes 6 files as "unknow" while for pes 4 with the correct name like BG_MUSIC

i leave you below the link for each file, i hope it helps! 

[http://www.mediafire.com/file/2ujdwma37ry8eg8/PES4_0_sound.rar/file](url)

[http://www.mediafire.com/file/andtg8qhybax6yj/PES5_0_sound.rar/file](url)

[http://www.mediafire.com/file/sevjovml8kvaqvv/PES6_0_sound.rar/file](url)

**Comment by MaikelChan** [comment]
Hi! Thanks for the report.

I've been taking a first look. AFS file from PES4 is pretty standard, so yeah, that should be working fine. However, for PES5, I've seen that the file contains some random data in unexpected places. It doesn't have file names information either, but the program can actually handle that properly for other games; it just extracts the files as "0000", "0001", "0002", etc. in those cases. So the problem is the random data.

I fixed that issue and I can extract the files correctly by just ignoring the random data. However, I'm worried that when recreating the file without that random data, it could not work in game. Would you be able to test? Here's a custom build:

[AFSPacker.zip](https://github.com/MaikelChan/AFSPacker/files/5453094/AFSPacker.zip)

Extract the PES5 AFS file with this version, and then recreate it again with `-c <folder> <output_afs_file> -nf`. The -nf parameter is important in this case in order to create an AFS file without file names (just like the original).

**Comment by moth1995** [comment]
Hi! now works perfectly, also i test to recreate it and i havent found any bug (this files only contains background music and public chants, at least those two works fine), sadly the names of files are not like pes4, i was hoping to find that because it will help me to understand much better the structure of some unknow files for the whole pes 5/6 community, anyways, thank you for your work!

Ps. i test it with -nf and without -nf parameter and works fine in both cases

**Comment by MaikelChan** [comment]
Yeah, some games don't store file names inside AFS files, so they're a bit of a pain in the ass to work with. But I'm glad that it's working now. Also, good to know that without the -nf parameter works too. I still recommend to use it though, as the generated AFS files will be a bit smaller due to the lack of file name information (information that is ignored by those games anyway).

**Comment by moth1995** [comment]
Hi maikel, sorry to bump into a closed issue, but i wanted to ask you, there is a chance that you could check back again the pes5 0_sound.afs? i notice that your tools doesnt export the file extension for that case, but for the one in pes4 it does, im using the lastest release, i tried with other tools like dkz, afs explorer and those two export the file extension, but i prefer yours since i can use it as a third party app :)
please tell me if you prefer that i open a new issue (also links above are still working)

**Comment by MaikelChan** [comment]
Hi! It's ok to follow the conversation in this issue.

In this case, this is intended. That AFS file doesn't contain any filename information, so it's up to the program developer to decide what name / extension to give to those unnamed files so they can be shown properly on Windows or other operating systems. I guess the program you mention decides to give the files an arbitrary extension. In my case, since the actual extension is unknown, I prefer to just leave them without it, to indicate that it's an unknown file.

But it's working as intended and you should be able to edit and reinsert the files with no problem.
